### PR TITLE
Wait for entire stream

### LINKED ISSUE #16: JSON.parse error
Sometimes when i try to change hue/saturation/brightness and power it throws that error: 
```
undefined:2
{"method":"props","params":{"power":"on"}}
^

SyntaxError: Unexpected token { in JSON at position 27
    at JSON.parse (<anonymous>)
    at Yeelight.formatResponse (/home/pi/Workspace/home-automation-server/node_modules/yeelight-wifi/build/Yeelight.js:153:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

For all cases in the same line Yeelight.js:153. Any ideas?

### PR DESCRIPTION
**Pull request by pemontto**
Closes #16

### CODE REVIEW

**Comment by pmdroid** [comment]
@pemontto please change the source code, not in the build folder.

**Comment by marvinroger** [comment]
@pemontto [there](https://github.com/pmdroid/yeelight-wifi/blob/master/src/Yeelight.js#L47)

**Comment by pmdroid** [comment]
@pemontto @marvinroger
tagged v2.0.0
released v2.0.0
try the new version

**Comment by marvinroger** [comment]
Awesome, thank you!

**Pull request merged**
